version: '3.8'

services:
  passport-monitoring-platform-connector:
    image: srdc/passport-monitoring-platform-connector:latest
    environment:
      CRON_SCHEDULE: "*/1 * * * *"
      PASSPORT_SERVER_URL: "http://passport-nginx:80/ai4hf/passport/api"
      STUDY_ID: "0197a6f8-2b78-71e4-81c1-b7b6a744ece3"
      CONNECTOR_SECRET: "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5ZTFiZTExNi0yMzg1LTRlZDctYTBiOC01ZDc0NWNjYzllOGMifQ.eyJpYXQiOjE3NTEyNzA4MjgsImp0aSI6ImIxMWE5NGI1LWQ5MzItNDhiNC1iMjc4LWFkZjQ1ZDJjMTMxOCIsImlzcyI6Imh0dHA6Ly9rZXljbG9hazo4MDgwL3JlYWxtcy9BSTRIRi1BdXRob3JpemF0aW9uIiwiYXVkIjoiaHR0cDovL2tleWNsb2FrOjgwODAvcmVhbG1zL0FJNEhGLUF1dGhvcml6YXRpb24iLCJzdWIiOiJkYXRhX3NjaWVudGlzdCIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJBSTRIRi1BdXRoIiwic2Vzc2lvbl9zdGF0ZSI6IjE3YzU2ZjhkLTljZmEtNDM2OC05MzQ4LTkzN2ZjY2QyMjY0ZCIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjE3YzU2ZjhkLTljZmEtNDM2OC05MzQ4LTkzN2ZjY2QyMjY0ZCJ9.obYaa744bmJoQAFO-nh1sCwPKwArWaOUo9_a1I0Uzc--HBuTLy6oOJVmnVI62bxnMkqoYo97SYGlKGKwVStz5g"
      LOGSTASH_URL: "http://ai4hf-monitoring-logstash:5000"
      TIMESTAMP_FILE: "/data/last_processed_timestamp.txt"
    volumes:
      - passport-monitoring-platform-connector-data:/data
    networks:
      - passport-network
      - ai4hf-monitoring

volumes:
  passport-monitoring-platform-connector-data:

networks:
  passport-network:
    name: passport-network
    external: true
  ai4hf-monitoring:
    name: ai4hf-monitoring
    driver: bridge