version: '3.8'

services:
  passport-monitoring-platform-connector:
    image: srdc/passport-monitoring-platform-connector:latest
    environment:
      CRON_SCHEDULE: "*/1 * * * *"
      PASSPORT_SERVER_URL: "http://passport-nginx:80/ai4hf/passport/api"
      STUDY_ID: "0197a6f8-2b78-71e4-81c1-b7b6a744ece3"
      CONNECTOR_SECRET: "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZGJiZjljYS0yMWQxLTRhZjYtODMwZi1hOGI0MDZjOWMxYTIifQ.eyJpYXQiOjE3NTIxMzA0NjAsImp0aSI6Ijk2MTQzZmMyLWE3YTctNGZhNi05YjliLWZhNGNmZTc0NzZkMSIsImlzcyI6Imh0dHA6Ly9rZXljbG9hazo4MDgwL3JlYWxtcy9BSTRIRi1BdXRob3JpemF0aW9uIiwiYXVkIjoiaHR0cDovL2tleWNsb2FrOjgwODAvcmVhbG1zL0FJNEhGLUF1dGhvcml6YXRpb24iLCJzdWIiOiJkYXRhX3NjaWVudGlzdCIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJBSTRIRi1BdXRoIiwic2Vzc2lvbl9zdGF0ZSI6ImQzYzFhZGE3LTVhNmUtNDE2Ni04ODNkLTEyODI5NGU0ZDFkZCIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MgcHJvZmlsZSBlbWFpbCIsInNpZCI6ImQzYzFhZGE3LTVhNmUtNDE2Ni04ODNkLTEyODI5NGU0ZDFkZCJ9.LkRHAk9krrde3ITGs6u_UNFJaZ-TGB6Na-yO300iT4roSinCcrM-e09lWN6pO8sPdNVQsbf-ojCQhXR_fJgAgQ"
      LOGSTASH_URL: "http://ai4hf-monitoring-logstash:5000"
      LOGSTASH_BASIC_AUTH: "bG9nc3Rhc2hfaW50ZXJuYWw6MnNnUWRIMEtySGE1YzJsUzBMR2c="
      TIMESTAMP_FILE: "/data/last_processed_timestamp.txt"
    volumes:
      - passport-monitoring-platform-connector-data:/data
    networks:
      - passport-network
      - ai4hf-monitoring

volumes:
  passport-monitoring-platform-connector-data:

networks:
  passport-network:
    name: passport-network
    external: true
  ai4hf-monitoring:
    name: ai4hf-monitoring
    driver: bridge