version: '3.8'

services:
  passport-monitoring-platform-connector:
    image: srdc/passport-monitoring-platform-connector:latest
    environment:
      CRON_SCHEDULE: "*/1 * * * *"
      PASSPORT_SERVER_URL: "http://passport-nginx:80/ai4hf/passport/api"
      STUDY_ID: "initial_study"
      USERNAME: "data_scientist"
      PASSWORD: "data_scientist"
      LOGSTASH_URL: "http://ai4hf-monitoring-logstash:5000"
      TIMESTAMP_FILE: "/data/last_processed_timestamp.txt"
    volumes:
      - passport-monitoring-platform-connector-data:/data
    networks:
      - passport-network
      - ai4hf-monitoring

volumes:
  passport-monitoring-platform-connector-data:

networks:
  passport-network:
    name: passport-network
    external: true
  ai4hf-monitoring:
    name: ai4hf-monitoring
    driver: bridge